[elixir] chore: new EDW.TRANSACTION_ORIGIN_DIMENSION table to ingest
mbta/data_platform pull request #122
Opened 2024-11-01 17:55 UTC by rymarczy

New table to ingest.

Following guide here: https://www.notion.so/mbta-downtown-crossing/Adding-a-New-Table-for-Ingestion-ec2f44a98f864a18929e4db4b48c931a

2024-11-01 19:23 UTC, grejdi-mbta approved these changes

2024-11-04 15:52 UTC, rymarczy commented
Updated the PR to migrate all tables mentioned in slack on Friday, the 1st.

2024-11-04 17:39 UTC, grejdi-mbta requested changes

2024-11-04 17:39 UTC, grejdi-mbta commented on ex_cubic_ingestion/priv/repo/migrations/20241104104113_add_even_more_ods_tables.exs
> +          s3_prefix: ods_table[:s3_prefix],
You forgot `is_active: true,`. See https://www.notion.so/mbta-downtown-crossing/Adding-a-New-Table-for-Ingestion-ec2f44a98f864a18929e4db4b48c931a

2024-11-04 18:30 UTC, rymarczy commented on ex_cubic_ingestion/priv/repo/migrations/20241104104113_add_even_more_ods_tables.exs
> +          s3_prefix: ods_table[:s3_prefix],
Incorporated.

2024-11-04 22:05 UTC, grejdi-mbta approved these changes

2024-11-05 14:58 UTC, merged