feat: check DMAP config values before running DMAP fetch process
mbta/data_platform pull request #97
Opened 2023-05-19 14:11 UTC by napilla

Asana ticket: [Put DMAP fetch process behind configuration flag, so we can deploy without it.](https://app.asana.com/0/0/1204592266198521/f)

Was able to run the existing tests with the DMAP config values defined and they passed - with the values empty I can see the following is logged:
`10:04:20.543 [error] [ex_cubic_ingestion] [workers] [schedule_dmap] Exception: args=%{} duration=75000 queue_time=-6000 state=failure attempt=1 kind=error error=%Oban.PerformError{message: "ExCubicIngestion.Workers.ScheduleDmap failed with {:error, \"dmap_base_url or dmap_api_key is empty, not running dmap job\"}", reason: {:error, "dmap_base_url or dmap_api_key is empty, not running dmap job"}} args_info=nil`

2023-05-19 14:31 UTC, paulswartz commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/schedule_dmap.ex
> +    try do
question: what is triggering this job? can we update that to not schedule the job at all if the DMAP environment is not configured?

2023-05-19 20:46 UTC, grejdi-mbta commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/schedule_dmap.ex
> +    dmap_base_url = Application.fetch_env!(:ex_cubic_ingestion, :dmap_base_url)
@napilla You'll need to update tests for this module.

2023-05-19 20:49 UTC, grejdi-mbta requested changes

2023-05-19 20:49 UTC, grejdi-mbta commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/schedule_dmap.ex
> +    if dmap_base_url == "" or dmap_api_key == "" do
@napilla In an effort to work on you elixir skills, there is probably an opportunity to us pattern matching here.

2023-05-22 16:47 UTC, napilla commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/schedule_dmap.ex
> +    dmap_base_url = Application.fetch_env!(:ex_cubic_ingestion, :dmap_base_url)
Since I'm doing the check elsewhere now (when grabbing Oban config item in application startup) I added another test that checks this method in `ScheduleDmapTest`

2023-05-22 16:47 UTC, napilla commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/workers/schedule_dmap.ex
> +    if dmap_base_url == "" or dmap_api_key == "" do
Thanks, I learned something here - let me know if my approach makes sense now

2023-05-22 18:31 UTC, paulswartz commented on ex_cubic_ingestion/lib/release_tasks/schedule_dmap.ex
> +      true ->
`case` with only booleans is clearer as an `if`. I think what @grejdi-mbta meant is something like:

```elixir
maybe_base_url = Application.fetch_env(:ex_cubic_ingestion, :dmap_base_url)
maybe_api_key = Application.fetch_env(:ex_cubic_ingestion, :dmap_base_url)

case {maybe_base_url, maybe_api_key} do
  {{:ok, base_url}, {:ok, api_key}} when base_url != "" and api_key != "" ->
    # configured
  _ ->
    # not configured
end
```

2023-05-22 18:57 UTC, napilla commented on ex_cubic_ingestion/lib/release_tasks/schedule_dmap.ex
> +          {:plugins, _} -> {:plugins, false}
I suppose none of them will be scheduled, if the dmap job isn't configured by then :) 

Good point, I'm wondering if it makes sense to define something that would build up the plugins (such as, we define the plugins as separate config items, and can add them into Oban as needed) that way whether or not we want to include this `ScheduleDmap` plugin can affect other plugins.

2023-05-22 19:01 UTC, grejdi-mbta requested changes

2023-05-22 19:01 UTC, grejdi-mbta commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/application.ex
> +      {Oban, ReleaseTasks.ScheduleDmap.oban_config()}
@napilla I feel like the other approach was better, just needed a little more cleanup (see Paul's comment). This structure assumes that Oban is only used for scheduling and that's not the truth. It actually allows for other jobs to be maintained. Lastly, per the AC in the Asana ticket, I'd like to have this logged every day that it's not running, not just when the app starts.

2023-05-22 19:16 UTC, napilla commented on ex_cubic_ingestion/lib/release_tasks/schedule_dmap.ex
> +          {:plugins, _} -> {:plugins, false}
Or, given this approach has implications on how we run other plugins, and to meet the ACs (see @grejdi-mbta's comment) it seems best to move forward with the check for the config values in `schedule_dmap.ex`

2023-05-23 11:27 UTC, napilla commented on ex_cubic_ingestion/lib/ex_cubic_ingestion/application.ex
> +      {Oban, ReleaseTasks.ScheduleDmap.oban_config()}
Thanks for the clarity, updated here. I updated the existing tests to check that the job wouldn't run as expected as well.

2023-05-23 12:46 UTC, grejdi-mbta requested changes

2023-05-23 12:46 UTC, grejdi-mbta commented on ex_cubic_ingestion/config/config.exs
> -        {"0 15 * * *", ExCubicIngestion.Workers.ScheduleDmap, max_attempts: 1}
@napilla Please revert this change. Might have been for you to test I believe.

2023-05-23 16:25 UTC, napilla commented on ex_cubic_ingestion/config/config.exs
> -        {"0 15 * * *", ExCubicIngestion.Workers.ScheduleDmap, max_attempts: 1}
Yes, was testing the job was running. My apologies and fixed in latest push

2023-05-23 16:36 UTC, grejdi-mbta approved these changes

2023-05-24 13:23 UTC, merged